FROM node:17-alpine

LABEL maintainer="Imre Faragó <imi.farago@gmail.com>"

WORKDIR /app

RUN apk --no-cache upgrade && \
    apk add git curl && \
    cd /app && \
    git clone https://github.com/tthdvd/laravel-echo-server.git . && \
    apk del git && \
    npm install && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY laravel-echo-server.json /app

COPY docker-entrypoint-whispers.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

ENTRYPOINT ["/app/docker-entrypoint.sh"]

VOLUME /app

EXPOSE 6001

HEALTHCHECK --interval=1m --timeout=5s \
CMD curl --fail http://localhost:6001 || exit 1

CMD ["start"]
